### ISSUE TITLE
mqtt hass.io

### ISSUE THREAD

**Issue by mike2nl** [crankyoldgit/Home-AssistantConfig#2]
@crankyoldgit 
You have this in your yaml files:
- stat/livingroom_fan/POWER
- cmd/livingroom_fan/POWER

May i ask if you are using Sonoff or Tuya devices in combination with Tasmota?

**Comment by crankyoldgit** [comment]
Yes, I am. I'm controlling a pedestal fan using a [Sonoff S20](https://www.itead.cc/smart-socket.html) running [Tasmota](https://github.com/arendst/Sonoff-Tasmota)

**Comment by mike2nl** [comment]
@crankyoldgit 
Ha, that's a real coincidence because...
- i'm coding for/with Tasmota to get more and more really good things running
- we, a team of good guys, work as admins on discord to help out other users to get things solved.
- i'm not the mqtt guy because my 2nd avatar name is SensorMike ;-).
- i work with many displays, sensors and safety for our work.
- my experience is over 32 years in industrial automation

Amazing to see that users do more then consume. You are doing a real good work!

About your fan: there is that iFan02 module. You have seen it?

**Comment by crankyoldgit** [comment]
> About your fan: there is that iFan02 module. You have seen it?

No, I haven't. As it is a simple switch, I didn't see the point of anything more than a simple on/off setup.
